### ISSUE TITLE
"Nonetype" object has no attribute '_getitem_' on Telugu & All Telugu Movies 

### ISSUE THREAD

**Issue by Phenom727** [irfancharania/plugin.video.india4movie#2]
Hello,
There seems to be an error - "Nonetype" object has no attribute '_getitem_' on Telugu & All Telugu Movies links on your addon.

If it can be fixed, it would be much appreciated. Thank you very much.

**Comment by LINGARAJUg** [comment]
Has been working fine on Asus Nexus player and windows 10 PC, recently installed on fire stick and I get parsing 0 error none type object has no something, any fix for this please, thank you.
