### ISSUE TITLE
Showing empty screen instead of main menu

### ISSUE THREAD

**Issue by ykhehra1** [irfancharania/plugin.video.india4movie#3]
Showing empty screen instead of main menu. May be something changed on site.

**Comment by irfancharania** [comment]
Looks like they changed the menu on their site.
I'll have a look at fixing it later. Unless you want to fix it and send a pull request?

**Comment by ykhehra1** [comment]
Its out of my scope, otherwise I would like to help.

**Comment by irfancharania** [comment]
They changed their menu again, and it's working...
